version: '3'

services:
  back:
    build: ./
    container_name: 'backend'
    ports:
      - '5500:5500'
  front:
    build:
      context: ../card-transfer
    container_name: 'front'
    ports:
      - '3000:3000'
